[package]
name = "EnclaveApp"
version = "0.0.1"
authors = ["jasl"]

[lib]
name = "enclaveapp"
crate-type = ["staticlib"]

[features]
default = []

[target.'cfg(not(target_env = "sgx"))'.dependencies]
sgx_types   = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tstd    = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk", features = ["net"] }
sgx_tcrypto = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_tse     = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_trts    = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }
sgx_rand    = { rev = "v1.0.8", git = "https://github.com/baidu/rust-sgx-sdk" }

[dependencies]
chrono      = { git = "https://github.com/mesalock-linux/chrono-sgx" }
webpki      = { git = "https://github.com/mesalock-linux/webpki", branch = "mesalock_sgx" }
base64      = { git = "https://github.com/mesalock-linux/rust-base64-sgx" }
yasna       = { git = "https://github.com/mesalock-linux/yasna.rs-sgx", features = ["bit-vec", "num-bigint", "chrono"] }
num-bigint  = { git = "https://github.com/mesalock-linux/num-bigint-sgx" }
bit-vec     = { version = "*", default-features = false}
httparse    = { version = "1.3.2", default-features=false }
itertools   = { version = "0.8" , default-features = false, features = []}
rustls      = { git = "https://github.com/mesalock-linux/rustls", branch = "mesalock_sgx" }
webpki-roots= { git = "https://github.com/mesalock-linux/webpki-roots", branch = "mesalock_sgx" }
serde = { git = "https://github.com/mesalock-linux/serde-sgx" }
serde_json = { git = "https://github.com/mesalock-linux/serde-json-sgx" }
lazy_static = { version = "1.1.0", features = ["spin_no_std"] }
libsecp256k1= { git = "https://github.com/mesalock-linux/libsecp256k1-rs-sgx" }
ring = { git = "https://github.com/mesalock-linux/ring-sgx", tag = "v0.14.6" }
