[dependencies]
alloc = {}
panic_unwind = {}
panic_abort = {}

[dependencies.sgx_types]
path = "../rust-sgx-sdk/sgx_types"
stage = 1

[dependencies.sgx_libc]
path = "../rust-sgx-sdk/sgx_libc"
stage = 2

[dependencies.sgx_tkey_exchange]
path = "../rust-sgx-sdk/sgx_tkey_exchange"
stage = 2

[dependencies.sgx_tservice]
path = "../rust-sgx-sdk/sgx_tservice"
stage = 2

[dependencies.sgx_tse]
path = "../rust-sgx-sdk/sgx_tse"
stage = 2

[dependencies.sgx_tcrypto]
path = "../rust-sgx-sdk/sgx_tcrypto"
stage = 2

[dependencies.sgx_trts]
path = "../rust-sgx-sdk/sgx_trts"
stage = 3

[dependencies.sgx_unwind]
path = "../rust-sgx-sdk/sgx_unwind"
stage = 4

[dependencies.sgx_tdh]
path = "../rust-sgx-sdk/sgx_tdh"
stage = 4

[dependencies.sgx_tseal]
path = "../rust-sgx-sdk/sgx_tseal"
stage = 4

[dependencies.sgx_tprotected_fs]
path = "../rust-sgx-sdk/sgx_tprotected_fs"
stage = 4

[dependencies.sgx_alloc]
path = "../rust-sgx-sdk/sgx_alloc"
stage = 4

[dependencies.std]
path = "../rust-sgx-sdk/xargo/sgx_tstd"
features = ["net"]
stage = 5

[dependencies.sgx_rand]
path = "../rust-sgx-sdk/sgx_rand"
stage = 6

[dependencies.sgx_serialize]
path = "../rust-sgx-sdk/sgx_serialize"
stage = 6

[dependencies.sgx_tunittest]
path = "../rust-sgx-sdk/sgx_tunittest"
stage = 6

[patch.crates-io]
libc = { git = "https://github.com/mesalock-linux/libc-sgx" }
